import React,{useEffect,useState} from 'react';
import {ShieldAlert,Phone,MapPin,CheckCircle,LocateFixed,Mail,MessageSquare,Clock} from 'lucide-react';
import api from '../api';

export default function SOS({user}){
 const [sent,setSent]=useState(false),[emailSent,setEmailSent]=useState(0),[smsSent,setSmsSent]=useState(0),[recipients,setRecipients]=useState([]),[history,setHistory]=useState([]),[busy,setBusy]=useState(false),[location,setLocation]=useState(null),[locationMsg,setLocationMsg]=useState('Location will be attached to the SOS when browser permission is granted.'),[message,setMessage]=useState('');
 useEffect(()=>{const load=()=>{if(user?.role==='patient')api.get('/emergency/my').then(r=>setHistory(r.data)).catch(()=>{});else api.get('/emergency/notifications').then(r=>setHistory(r.data)).catch(()=>{})};load();const t=setInterval(load,10000);return()=>clearInterval(t)},[user]);
 const getLocation=()=>new Promise(resolve=>{if(!navigator.geolocation){setLocationMsg('This browser does not support location.');return resolve(null)}setLocationMsg('Getting your location…');navigator.geolocation.getCurrentPosition(pos=>{const l={latitude:pos.coords.latitude,longitude:pos.coords.longitude,accuracy:pos.coords.accuracy};setLocation(l);setLocationMsg(`Location ready (accuracy about ${Math.round(l.accuracy)} m).`);resolve(l)},()=>{setLocationMsg('Location permission was not granted. SOS can still be sent without coordinates.');resolve(null)},{enableHighAccuracy:true,timeout:10000,maximumAge:0})});
 const send=async()=>{setBusy(true);try{const l=location||await getLocation();const r=await api.post('/emergency/sos',{...(l||{}),message:message.trim()||undefined});setHistory(h=>[r.data,...h]);setEmailSent(r.data.emailsSent||0);setSmsSent(r.data.smsSent||0);setRecipients(r.data.recipients||[]);setSent(true)}catch(e){alert(e.response?.data?.message||'Could not send alert')}finally{setBusy(false)}};
 if(user?.role!=='patient')return <div className="page"><div className="page-head"><div><span className="pill danger-pill">Emergency monitoring</span><h1>Patient SOS alerts</h1><p>New SOS events from your assigned patients appear here automatically.</p></div></div><div className="panel"><h3><ShieldAlert/> Live emergency alerts</h3><p className="muted">Each alert can include the patient's phone, email and GPS location. Use the contact buttons for a direct call or email.</p>{history.map(a=><div className="alert-row" key={a._id}><div><b>🚨 SOS from {a.patientId?.name||'Patient'}</b><small><Clock size={13}/> {new Date(a.createdAt).toLocaleString()} • {a.message}</small><div className="alert-contact">{a.patientId?.phone&&<a href={`tel:${a.patientId.phone}`}><Phone size={13}/> {a.patientId.phone}</a>}{a.patientId?.email&&<a href={`mailto:${a.patientId.email}`}><Mail size={13}/> {a.patientId.email}</a>}</div>{a.mapUrl&&<a className="sos-location-link" href={a.mapUrl} target="_blank" rel="noreferrer"><MapPin size={14}/> View patient location</a>}</div><span className={`badge ${a.status==='active'?'high':'low'}`}>{a.status}</span></div>)}{!history.length&&<p className="muted">No emergency alerts yet.</p>}</div></div>;
 return <div className="page"><div className="page-head"><div><span className="pill danger-pill">Emergency SOS</span><h1>Need immediate help?</h1><p>Send an alert to your linked doctor and caregivers. The alert can be delivered by dashboard, email and SMS when those services are configured.</p></div></div><div className="sos-panel"><ShieldAlert size={80}/><h2>{sent?'Alert sent successfully':'Emergency assistance'}</h2><p>{sent?'Your care team can now see this alert.':'Press the button only for a genuine emergency.'}</p>{sent&&<><div className="success"><CheckCircle size={17}/> Dashboard alert created • Email sent: <b>{emailSent}</b> • SMS sent: <b>{smsSent}</b></div>{recipients.length>0&&<div className="sos-contact-list">{recipients.map((c,i)=><div className="sos-contact" key={`${c.email}-${c.phone}-${i}`}><div><b>{c.name}</b><small>{c.role}</small></div><div className="contact-links">{c.phone&&<a href={`tel:${c.phone}`}><Phone size={13}/> Call</a>}{c.email&&<a href={`mailto:${c.email}`}><Mail size={13}/> Email</a>}</div></div>)}</div>}</>}
 <div className="location-status"><LocateFixed size={18}/><span>{locationMsg}</span>{location?.latitude&&<a href={`https://www.google.com/maps?q=${location.latitude},${location.longitude}`} target="_blank" rel="noreferrer">View my location</a>}</div><textarea className="sos-message" value={message} onChange={e=>setMessage(e.target.value)} placeholder="Optional: describe what help is needed (for example: I feel dizzy and need assistance)." rows={3}/>
 <button className="secondary" onClick={getLocation} disabled={busy}><MapPin/> Get current location</button><button className="sos-button" disabled={busy} onClick={send}><ShieldAlert/> {busy?'Sending…':sent?'SEND ANOTHER SOS':'SEND SOS ALERT'}</button><div className="sos-info"><span><Phone/> Doctor + caregiver phone alerts</span><span><Mail/> Doctor + caregiver email alerts</span><span><MapPin/> GPS coordinates attached when available</span></div></div>
 <section className="panel"><h3>Recent SOS alerts</h3>{history.map(a=><div className="patient-row" key={a._id}><div><b>{new Date(a.createdAt).toLocaleString()}</b><small>{a.message}</small>{a.latitude&&<a className="text-link" target="_blank" rel="noreferrer" href={a.mapUrl||`https://www.google.com/maps?q=${a.latitude},${a.longitude}`}>📍 View location</a>}</div><span className={`badge ${a.status==='active'?'high':'low'}`}>{a.status}</span></div>)}{!history.length&&<p className="muted">No SOS alerts yet.</p>}</section></div>
}
