import React,{useEffect,useRef,useState} from 'react';import {Mic,Volume2,MessageCircle,StopCircle} from 'lucide-react';import {useNavigate} from 'react-router-dom';
function safeCalculate(expression){
 const tokens=expression.replace(/\s+/g,'').match(/(?:\d+(?:\.\d+)?|[()+\-*/])/g);
 if(!tokens||tokens.join('')!==expression.replace(/\s+/g,''))throw new Error('invalid expression');
 const values=[],ops=[];const prec={'+':1,'-':1,'*':2,'/':2};
 const apply=()=>{const op=ops.pop();const b=values.pop();const a=values.pop();if(op==='/'&&b===0)throw new Error('division by zero');values.push(op==='+'?a+b:op==='-'?a-b:op==='*'?a*b:a/b)};
 for(let i=0;i<tokens.length;i++){const t=tokens[i];if(/^\d/.test(t)){values.push(Number(t));continue}if(t==='('){ops.push(t);continue}if(t===')'){while(ops.length&&ops.at(-1)!=='(')apply();if(ops.pop()!=='(')throw new Error('bad parentheses');continue}while(ops.length&&ops.at(-1)!=='('&&prec[ops.at(-1)]>=prec[t])apply();ops.push(t)}while(ops.length){if(ops.at(-1)==='(')throw new Error('bad parentheses');apply()}if(values.length!==1||!Number.isFinite(values[0]))throw new Error('invalid result');return values[0];}

export default function Voice({user}){const [text,setText]=useState('');const [reply,setReply]=useState('');const [listening,setListening]=useState(false);const recognition=useRef(null);const nav=useNavigate();
 const speak=t=>{setReply(t);if('speechSynthesis'in window){window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang=user?.language==='Hindi'?'hi-IN':'en-IN';window.speechSynthesis.speak(u)}};
 const respond=raw=>{const q=raw.toLowerCase().trim();let answer='';if(/^(hi|hello|hey|namaste)/.test(q))answer='Hello! I am your MindCare voice assistant. Tell me what you would like me to do.';else if(q.includes('time'))answer=`The current time is ${new Date().toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}.`;else if(q.includes('date')||q.includes('today'))answer=`Today is ${new Date().toLocaleDateString([], {weekday:'long',month:'long',day:'numeric',year:'numeric'})}.`;else if(q.includes('go home')||q.includes('dashboard')||q.includes('open dashboard')){nav('/');answer='Opening your dashboard.'}else if(q.includes('game')||q.includes('play')){nav('/games');answer='Opening cognitive games.'}else if(q.includes('medicine')||q.includes('reminder')||q.includes('tablet')){nav('/reminders');answer='Opening your medicine routine.'}else if(q.includes('check-up')||q.includes('checkup')||q.includes('assessment')){nav('/assessment');answer='Opening your daily check-up.'}else if(q.includes('profile')){nav('/profile');answer='Opening your profile.'}else if(q.includes('emergency')||q.includes('sos')||q.includes('help me')){nav('/sos');answer='Opening emergency SOS. Press the SOS button only when you need emergency assistance.'}else if(q.includes('back')){window.history.back();answer='Going back.'}else if(q.includes('forward')){window.history.forward();answer='Going forward.'}else if(q.includes('refresh')||q.includes('reload')){answer='Refreshing the page.';setTimeout(()=>window.location.reload(),500)}else if(/^\s*(what can you do|help)\s*\??$/.test(q))answer='I can help with general instructions, website navigation, time and date, simple calculations, and reading my response aloud.';else{const calc=q.match(/(?:what is|calculate|compute)\s+([0-9+\-*/().% ]+)\??$/);if(calc){try{const expr=calc[1].replace(/%/g,'/100');if(/^[0-9+\-*/().\s]+$/.test(expr))answer=`The answer is ${safeCalculate(expr)}.`;else answer='I could not safely calculate that expression.'}catch{answer='I could not calculate that. Please try a simpler calculation.'}}else answer=`I heard: ${raw}. I can help with general instructions and website actions. Say help for examples.`}speak(answer)};
 const listen=()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){speak('Voice recognition is not supported in this browser. Please use Chrome or another browser with Web Speech support.');return}if(listening){recognition.current?.stop();return}const r=new SR();recognition.current=r;r.lang=user?.language==='Hindi'?'hi-IN':'en-IN';r.interimResults=false;r.continuous=false;r.onstart=()=>setListening(true);r.onend=()=>setListening(false);r.onerror=()=>{setListening(false);speak('I could not hear that clearly. Please try again.')};r.onresult=e=>{const t=e.results[0][0].transcript;setText(t);respond(t)};r.start()};
 useEffect(()=>()=>{recognition.current?.stop();window.speechSynthesis?.cancel()},[]);return <div className="page"><div className="page-head"><div><span className="pill">General Voice Assistant</span><h1>Talk to MindCare</h1><p>Give instructions naturally. This assistant is not limited to medicine or games.</p></div></div><div className="panel voice"><div className={`mic ${listening?'listening':''}`} onClick={listen}>{listening?<StopCircle size={55}/>:<Mic size={55}/>}</div><h2>{listening?'Listening…':'Tap the microphone'}</h2><p className="muted">Try “open my profile”, “what time is it?”, “go back”, “refresh”, or any other instruction.</p>{text&&<div className="voice-result"><MessageCircle/><div><b>You said</b><span>{text}</span></div><button className="icon" onClick={()=>speak(reply||text)}><Volume2/></button></div>}{reply&&<div className="voice-result assistant"><MessageCircle/><div><b>MindCare</b><span>{reply}</span></div></div>}</div><div className="note">Voice recognition uses your browser's speech service. It does not require a domain-specific command list to start listening.</div></div>}
