import {Router} from 'express';import {supabase,assessmentFromRow,userFromRow} from '../utils/supabase.js';import {auth} from '../middleware/auth.js';import {cognitivePrediction,medicationAdherence} from '../utils/aiEngine.js';
const r=Router();
async function one(table,filters,order='created_at',limit=1){let q=supabase.from(table).select('*');for(const [k,v] of Object.entries(filters))q=q.eq(k,v);if(order)q=q.order(order,{ascending:false});q=q.limit(limit);const {data,error}=await q;if(error)throw error;return data||[]}
r.post('/',auth,async(req,res)=>{try{const {memory=0,attention=0,orientation=0,language=0,reactionTimeMs=700,game,gameAccuracy}=req.body;const allowedGames=['Memory Match','Find the Number','Memory Pattern','Visual Memory','Word Recall','Number Recall'];const selectedGame=allowedGames.includes(game)?game:'Memory Match';const games=await one('game_results',{user_id:req.user.id,game:selectedGame});const {data:reminders,error:re}=await supabase.from('reminders').select('*').eq('user_id',req.user.id);if(re)throw re;const reminderRows=(reminders||[]).map(x=>({...x,userId:x.user_id,notifyEmail:x.notify_email,notifySms:x.notify_sms,missedCount:x.missed_count,takenAt:x.taken_at,lastNotifiedKey:x.last_notified_key}));const med=medicationAdherence(reminderRows);const acc=Number.isFinite(Number(gameAccuracy))?Number(gameAccuracy):(games.length?Number(games[0].accuracy??games[0].score??0):75);const ai=cognitivePrediction({memory,attention,orientation,language,reactionTimeMs,gameAccuracy:acc,sleepHours:7,medicationAdherence:med.score});const total=memory+attention+orientation+language;const {data,error}=await supabase.from('assessments').insert({user_id:req.user.id,memory,attention,orientation,language,total,game:selectedGame,game_accuracy:acc,ai_risk:ai.priority,ai_probability:ai.probability,ai_reasons:ai.reasons,ai_recommendation:ai.recommendation,ai_action:ai.action,reaction_time_ms:reactionTimeMs}).select('*').single();if(error)throw error;const a=assessmentFromRow(data);res.status(201).json({...a,aiModel:ai.model,trainedOn:ai.trainedOn,aiRecommendation:ai.recommendation,aiAction:ai.action})}catch(e){res.status(500).json({message:e.message})}});
r.get('/',auth,async(req,res)=>{try{let userId=req.user.id;if(req.user.role!=='patient'){if(!req.query.patientId)return res.status(400).json({message:'patientId is required'});const filter=req.user.role==='doctor'?{id:req.query.patientId,role:'patient',doctor_id:req.user.id}:{id:req.query.patientId,role:'patient',caregiver_id:req.user.id};const {data:p,error}=await supabase.from('users').select('*').match(filter).maybeSingle();if(error)throw error;if(!p)return res.status(403).json({message:'Patient is not assigned to you'});userId=p.id}const rows=await one('assessments',{user_id:userId},'created_at',12);res.json(rows.map(assessmentFromRow))}catch(e){res.status(500).json({message:e.message})}});
r.get('/patients',auth,async(req,res)=>{try{if(!['doctor','caregiver'].includes(req.user.role))return res.status(403).json({message:'Not allowed'});let q=supabase.from('users').select('*').eq('role','patient');if(req.user.role==='doctor')q=q.eq('doctor_id',req.user.id).eq('doctor_request_status','accepted');else q=q.eq('caregiver_id',req.user.id).eq('doctor_request_status','accepted');const {data:patients,error}=await q; if(error)throw error;const data=await Promise.all((patients||[]).map(async p=>({patient:{...userFromRow(p),_id:p.id},latest:assessmentFromRow((await one('assessments',{user_id:p.id}))[0]||null)})));res.json(data)}catch(e){res.status(500).json({message:e.message})}});
r.get('/report/:patientId',auth,async(req,res)=>{try{
 if(!['doctor','caregiver'].includes(req.user.role))return res.status(403).json({message:'Professional only'});
 const filter=req.user.role==='doctor'?{id:req.params.patientId,role:'patient',doctor_id:req.user.id,doctor_request_status:'accepted'}:{id:req.params.patientId,role:'patient',caregiver_id:req.user.id,doctor_request_status:'accepted'};
 const {data:patient,error:pe}=await supabase.from('users').select('*').match(filter).maybeSingle();if(pe)throw pe;if(!patient)return res.status(404).json({message:'Patient is not assigned to you'});
 const [a,g,m]=await Promise.all([
   supabase.from('assessments').select('*').eq('user_id',patient.id).order('created_at',{ascending:false}).limit(20),
   supabase.from('game_results').select('*').eq('user_id',patient.id).order('created_at',{ascending:false}).limit(30),
   supabase.from('reminders').select('*').eq('user_id',patient.id).order('time',{ascending:true})
 ]);
 if(a.error)throw a.error;if(g.error)throw g.error;if(m.error)throw m.error;
 const reminders=(m.data||[]).map(x=>({...x,userId:x.user_id,notifyEmail:x.notify_email,notifySms:x.notify_sms,takenAt:x.taken_at,missedCount:x.missed_count}));
 res.json({patient:userFromRow(patient),assessments:(a.data||[]).map(assessmentFromRow),games:(g.data||[]).map(x=>({...gameFromRow(x)})),reminders,medicineAI:medicationAdherence(reminders)});
}catch(e){res.status(500).json({message:e.message})}});
export default r;
