import React,{useEffect,useState} from 'react';
import api from '../api';

export default function MedicineNotifier({user}){
 const [reminders,setReminders]=useState([]);const [alert,setAlert]=useState(null);
 useEffect(()=>{if(user?.role!=='patient')return;let alive=true;const load=async()=>{try{const r=await api.get('/reminders');if(alive)setReminders(r.data||[])}catch{}};load();const id=setInterval(load,30000);return()=>{alive=false;clearInterval(id)}},[user]);
 useEffect(()=>{if(user?.role!=='patient')return;const check=()=>{const now=new Date();const hm=String(now.getHours()).padStart(2,'0')+':'+String(now.getMinutes()).padStart(2,'0');const day=[now.getFullYear(),String(now.getMonth()+1).padStart(2,'0'),String(now.getDate()).padStart(2,'0')].join('-');const due=reminders.find(x=>x.time===hm&&!x.taken&&localStorage.getItem(`medicine-notified-${x._id}-${day}`)!=='1');if(!due)return;localStorage.setItem(`medicine-notified-${due._id}-${day}`,'1');setAlert(due);if('Notification'in window&&Notification.permission==='granted')new Notification('🔔 Medicine Reminder',{body:`${due.medicine}${due.dosage?' — '+due.dosage:''}\nIt is time to take your medicine.`});};check();const id=setInterval(check,1000);return()=>clearInterval(id)},[reminders,user]);
 useEffect(()=>{if(user?.role==='patient'&&'Notification'in window&&Notification.permission==='default')Notification.requestPermission().catch(()=>{})},[user]);
 if(!alert)return null;const taken=async()=>{try{await api.patch('/reminders/'+alert._id,{taken:true});setReminders(x=>x.map(r=>r._id===alert._id?{...r,taken:true}:r));setAlert(null)}catch{}};const later=()=>{const now=new Date();const day=[now.getFullYear(),String(now.getMonth()+1).padStart(2,'0'),String(now.getDate()).padStart(2,'0')].join('-');localStorage.removeItem(`medicine-notified-${alert._id}-${day}`);setAlert(null);setTimeout(()=>{setAlert({...alert,_snoozed:true})},10*60*1000)};
 return <div className="medicine-popup"><div className="medicine-popup-icon">💊</div><div><span className="pill">Medicine Reminder</span><h3>{alert.medicine}</h3><p>{alert.dosage||'Prescribed medicine'}{alert.instructions?` • ${alert.instructions}`:''}</p><strong>It’s time to take your medicine.</strong><div className="popup-actions"><button className="primary" onClick={taken}>✓ Taken</button><button className="secondary" onClick={later}>⏰ Remind me later</button></div></div><button className="popup-close" onClick={()=>setAlert(null)}>×</button></div>
}
